otbr:
  container_name: otbr
  image: openthread/otbr:latest
  restart: unless-stopped
  # network_mode: host
  privileged: true
  sysctls:
    net.ipv6.conf.all.disable_ipv6: 0
    net.ipv4.conf.all.forwarding: 1
    net.ipv6.conf.all.forwarding: 1
  dns:
    - 127.0.0.1
  stdin_open: true
  tty: true
  volumes:
    - otbr-data:/var/lib/otbr
    - otbr-wpantund:/etc/wpantund.conf
    - otbr-config:/etc/otbr
  ports: # For reference only. Thread requires these ports.
    - "8283:8283"
  command: >
    --radio-url spinel+hdlc+uart:///dev/ttyX # Example

